doc: updated documentation examples
bengeisler/TcLog pull request #23
Opened 2024-05-30 19:47 UTC by seehma

newer TwinCAT versions require namespace access therefore added the namespace to all code examples

2024-05-30 19:49 UTC, bengeisler approved these changes

2024-05-30 20:36 UTC, bengeisler commented
Thanks for your contribution! 

With the [latest release](https://github.com/bengeisler/TcLog/releases/tag/v0.5.0) however, the namespace has changes to `TcLogLib`. Please update the PR. 

Anyway, this release seems to solve #22 and #21, so maybe we'll just leave the docs as they are?

2024-05-30 20:37 UTC, bengeisler requested changes
Thanks for your contribution! 

With the [latest release](https://github.com/bengeisler/TcLog/releases/tag/v0.5.0) however, the namespace has changes to `TcLogLib`. Please update the PR. 

Anyway, this release seems to solve #22 and #21, so maybe we'll just leave the docs as they are?

2024-05-31 05:21 UTC, seehma commented
I updated the documentation. Of course its your choice how to deal with it, we install our libraries (Zeugwerk Framework) always with namespace required. Also Beckhoff often had problems on solving dependency things from libraries without namespace, sometimes it worked well, on some TwinCAT versions the compiler threw error messages. With Qualified access only, the problems were gone.
However, thanks for fixing it, i didnt had the time to take a closer look on it, my workaround with qualified access only was a quick fix :-)

2024-05-31 07:38 UTC, merged